"""Central paths and runtime constants for the Mosca simulation."""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
HOST = "0.0.0.0"
PORT = 8000
STATIC_DIRECTORY = PROJECT_ROOT / "static"
DATA_DIRECTORY = PROJECT_ROOT / "data"
PROFILES_DIRECTORY = DATA_DIRECTORY / "profiles"
LOGS_DIRECTORY = DATA_DIRECTORY / "logs"
SKELETONS_DIRECTORY = DATA_DIRECTORY / "neuron_skeletons"
CIRCUIT_DATA_PATH = PROJECT_ROOT / "circuit_data.json"
CUSTOM_PROFILE_WEIGHTS = PROFILES_DIRECTORY / "custom_profile_weights.json"

ARENA_WIDTH = 10.0
ARENA_DEPTH = 10.0
ARENA_HEIGHT = 4.0
ARENA_X_BOUNDS = (-ARENA_WIDTH / 2, ARENA_WIDTH / 2)
ARENA_Y_BOUNDS = (-ARENA_DEPTH / 2, ARENA_DEPTH / 2)
ARENA_Z_BOUNDS = (0.0, ARENA_HEIGHT)
ODOR_POSITION_BOUNDS = ((-4.0, 4.0), (-4.0, 4.0), (0.5, 2.5))
DEFAULT_WIND_SPEED = 0.0
WIND_ANGLE_DEG = 0.0
DEFAULT_FLYING_METABOLIC_RATE = 1.0
BASE_FLY_ENERGY_COST = 0.5

STEP_SECONDS = 0.01
DT_MS = 5.0
BASELINE_CURRENT_PA = 125.0
MAX_CURRENT_PA = 350.0
SENSOR_GAIN = 450.0
MOTOR_GAIN = 0.02
FORWARD_STEP = 0.02
REWARD_DISTANCE = 0.6
US_CURRENT_PA = 700.0
TRIAL_DURATION_MS = 30_000.0
